
spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/nksinh51018/configQlsc
               username: nksinh51018@gmail.com
               password: Akthangga1@

server:
   port: 8761

eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
management:
   endpoints:
      web:
         exposure:
            include: "*"