
server:
   port: 9100
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/nguoidung
      username: root
      password: Akthangga1
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
databaseName: nguoidung
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/