server:
  port: 8087
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
#server:
#port: 8082
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/report
      username: root
      password: root
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
databaseName: sanpham
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/